spring:
  jpa:
    hibernate:
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
    show-sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://mysql-server:3306/pms_master?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
    druid:
      validation-query: select 1
ftp:
  domain: http://www.file-server.com/
  path: bsc/
  host: 192.168.1.142
  port: 21
  username: ftpuser
  password: ftpuser
sms:
  ipyy:
    signature: 【Tinfo】
    account: XPT30095
    password: XPT3009595
dingtalk:
  appid: dingoaugcl42xapwtntrkh
  appsecret: ahTZfAxGtKUrSprLS2eeRbbaEIjtiRRhrdWD_epV7GDcRDbaDVraxn-SOQ5tNCiN
  service: https://oapi.dingtalk.com
  ldomain: https://login.dingtalk.com
  domain: http://tinfo.trm-cloud.com
  getuserinfo_bycode: /sns/getuserinfo_bycode
  redirect_uri: /dingtalk_login
  login_url: https://oapi.dingtalk.com/connect/oauth2/sns_authorize?appid=${dingtalk.appid}&response_type=code&scope=snsapi_login&state=STATE&redirect_uri=${dingtalk.domain}${dingtalk.redirect_uri}
